[package]
name = "sdl2_window"
version = "0.1.0"
edition = "2021"

[[bin]]
name="chip8"
path="src/main.rs"

[dependencies]
emulator = { path = "../emulator" }

[dependencies.sdl2]
version="0.36.0"
features=["bundled"]
